#!/usr/bin/python

####################################################################
#                __       ____   ____           .__  _____         #
#  ______ ______/  |______\   \ /   /___________|__|/ ____\__.__.  #
# /  ___//     \   __\____ \   Y   // __ \_  __ \  \   __<   |  |  #
# \___ \|  Y Y  \  | |  |_> >     /\  ___/|  | \/  ||  |  \___  |  #
# /____  >__|_|  /__| |   __/ \___/  \___  >__|  |__||__|  / ____| #
#      \/      \/     |__|               \/                \/      #
#                                                                  #
####################################################################


import socket
import sys 

if len(sys.argv) != 2:
	print "Usage: vrfy.py <username>"
	sys.exit(0)
	
# create a socket
s=socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# connect to the server
connect=s.connect(('10.11.1.215',25))

# receive the banner
banner=s.recv(1024)
print banner

# VRFY a user
s.send('VRFY' + sys.argv[1] + '\r\n')
result=s.recv(1024)
print result

# close the socket
s.close()
